version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    environment:
      MONGO_URI: "mongodb://mongodb:27017/url-shortener"

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
