apiVersion: apps/v1
kind: Deployment
metadata:
  name: url-shortener
spec:
  replicas: 2
  selector:
    matchLabels:
      app: url-shortener
  template:
    metadata:
      labels:
        app: url-shortener
    spec:
      containers:
        - name: url-shortener
          image: mukta05/url-shortener:v1  # Replace with actual image
          ports:
            - containerPort: 3000
      imagePullSecrets:
        - name: regcred